/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import javax.swing.JOptionPane;

/**
 *
 * @author mrs_a
 */
public class Form_Calc extends javax.swing.JPanel {



    public Form_Calc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_resultado = new javax.swing.JLabel();
        cb_substrato = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cb_pesoTinta = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_inkCoverage = new javax.swing.JTextField();
        txt_qtdFolha = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cb_acabamentoVerniz = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        btn_info = new javax.swing.JButton();
        btn_Calcular = new javax.swing.JButton();
        btn_Limpar = new javax.swing.JButton();

        lb_resultado.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lb_resultado.setForeground(new java.awt.Color(0, 153, 255));
        lb_resultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_resultado.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        cb_substrato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cartão Copo", "Cartão Couché", "Cartão Coated", "Cartão Uncoated", "Cartão Laminado", "Papel Sulfite" }));
        cb_substrato.setSelectedIndex(2);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Substrato");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Peso Específico da tinta");

        cb_pesoTinta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CMYK", "CMYK UV", "Escala Pantone", "Tons Pastéis", "Metalizado", "Branco Opaco" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("(*)Ink Coverage mm²");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("(*)Quantidade");

        txt_inkCoverage.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt_qtdFolha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_qtdFolha.setToolTipText("Digite a quantidade de produto para Prefligh ou Tiragem de impressão para Postfligh ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Acabamento Verniz");

        cb_acabamentoVerniz.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Brilho", "Fosco" }));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel9.setText("(*)Preenchimento obrigatório");

        btn_info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/info.png"))); // NOI18N
        btn_info.setToolTipText("Informações");
        btn_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_infoActionPerformed(evt);
            }
        });

        btn_Calcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/calcular.png"))); // NOI18N
        btn_Calcular.setToolTipText("Calcular");
        btn_Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CalcularActionPerformed(evt);
            }
        });

        btn_Limpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reiniciar.png"))); // NOI18N
        btn_Limpar.setToolTipText("Reiniciar/Limpar");
        btn_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_resultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cb_substrato, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cb_pesoTinta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_inkCoverage, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_qtdFolha, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cb_acabamentoVerniz, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_info)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(btn_Limpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(btn_Calcular)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(0, 0, 0)
                .addComponent(cb_substrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(0, 0, 0)
                .addComponent(cb_pesoTinta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(0, 0, 0)
                .addComponent(cb_acabamentoVerniz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(0, 0, 0)
                .addComponent(txt_inkCoverage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(0, 0, 0)
                .addComponent(txt_qtdFolha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_info)
                    .addComponent(btn_Calcular)
                    .addComponent(btn_Limpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LimparActionPerformed

        lb_resultado.setText("");
        cb_pesoTinta.setSelectedIndex(0);
        cb_substrato.setSelectedIndex(2);
        cb_acabamentoVerniz.setSelectedIndex(0);
        txt_inkCoverage.setText("");
        txt_qtdFolha.setText("");
    }//GEN-LAST:event_btn_LimparActionPerformed

    private void btn_CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CalcularActionPerformed

        if ("".equals(txt_inkCoverage.getText())) {
            JOptionPane.showMessageDialog(null, "Informe o valor do Ink Coverage!", "", 2);
        } else {
            if ("".equals(txt_qtdFolha.getText())) {
                JOptionPane.showMessageDialog(null, "Informe a quantidade!", "", 2);
            } else {
                float s = 0, p = 0, a = 0, i = 0, n = 0, sg = 0;
                switch (cb_substrato.getSelectedIndex()) {
                    case 0:
                        s = (float) 1.0;
                        break;
                    case 1:
                        s = (float) 1.2;
                        break;
                    case 2:
                        s = (float) 1.5;
                        break;
                    case 3:
                        s = (float) 2.0;
                        break;
                    case 4:
                        s = (float) 2.0;
                        break;
                    case 5:
                        s = (float) 1.6;
                        break;
                }

                switch (cb_pesoTinta.getSelectedIndex()) {
                    case 0:
                        sg = (float) 1;
                        break;
                    case 1:
                        sg = (float) 1.2;
                        break;
                    case 2:
                        sg = (float) 1.7;
                        break;
                    case 3:
                        sg = (float) 2.0;
                        break;
                    case 4:
                        sg = (float) 2.3;
                        break;
                    case 5:
                        sg = (float) 2.5;
                        break;
                }

                switch (cb_acabamentoVerniz.getSelectedIndex()) {
                    case 0:
                        a = (float) 1.0;
                        break;
                    case 1:
                        a = (float) 1.2;
                        break;
                }

                i = (Float.parseFloat(txt_inkCoverage.getText().replace(",", "."))) / 1000000;
                n = Float.parseFloat(txt_qtdFolha.getText().replace(",", "."));
                p = (float) 0.5;
                float resultado = (s * p * a * i * n * sg) / 353;
                lb_resultado.setText(String.format("%.2f", resultado) + "Kg");
            }
        }
    }//GEN-LAST:event_btn_CalcularActionPerformed

    private void btn_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_infoActionPerformed
     
    }//GEN-LAST:event_btn_infoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Calcular;
    private javax.swing.JButton btn_Limpar;
    private javax.swing.JButton btn_info;
    private javax.swing.JComboBox<String> cb_acabamentoVerniz;
    private javax.swing.JComboBox<String> cb_pesoTinta;
    private javax.swing.JComboBox<String> cb_substrato;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lb_resultado;
    private javax.swing.JTextField txt_inkCoverage;
    private javax.swing.JTextField txt_qtdFolha;
    // End of variables declaration//GEN-END:variables
}
